appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EBc4RT/qyk1Sz07XmDmgCDHgKOl3DT2uy5wN2gSLzcXFyxdDB521Et/sGqYnsJQFJ+q1cYLg3dF4L7PX2XAg0VEt+atW6j/+xIqSNhsEYQrHOdb7BmjcPiqWuIYqndZSr+pMX+KzGAhYSAa8wjnkR0EIN/xhmQlv4cSRonr9us9lbBr7/f8wzIpko04LAk7RuSVjNmsgsQT9QD5kG8i6ahHnbPzOlNe8H+hFGSPWqpekZe8wdeVWUhGgdbovGUhx9u6eVf9zIg+ti3JBIx23ee1De3BqGF74vv1qgmrEnn0tmzqNkSDo72L4uSf6akn8gfr5Jm0q8lhIzH79y+qjH/B0u2TINnqtgYIHjbi939HhXU5Lih/vMVi5psNRRy/0x9rM6kY8SLeD7GOU9odpXDjCY3WuPus+hd4+9KXWCN1X3c4yE37XlOH1lk8lzwZstVdbLGjcE/WlMHDPeovuxpW963KkmWjyXzTohjzI/Yqpa8C78eBZDNuKVo8/5A0QaesXVPTNwSDVYgx3WzC/0I1HD0J9JWhoIKtf7V4G6q/d1YbpshX41iQP3z176gD4t2Fa/B3z3DtRZWCzOKrhBi9mi4mqSEmUbMPW1fE59nW9ghTx/e1LQCbs+fN3pox/07khvUDylsaNMoQ3ilXLzzYuy8mwSaLFn8P+CvjY+eQ=}
